# File: docker-compose.yaml

services:
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: semantica-rabbitmq
    ports:
      - "${RABBITMQ_HOST_AMQP_PORT:-5672}:5672" # AMQP порт
      - "${RABBITMQ_HOST_MANAGEMENT_PORT:-15672}:15672" # Management UI порт
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Сохранение данных RabbitMQ
    environment:
      # Используем значения из .env или значения по умолчанию, если в .env нет
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s # Даем время на запуск перед первой проверкой
    restart: unless-stopped
    networks:
      - semantica_network

  postgres:
    image: postgres:16-alpine
    container_name: semantica-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # Обязательно должны быть в .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Обязательно должны быть в .env
      POSTGRES_DB: ${POSTGRES_DB} # Обязательно должны быть в .env
    volumes:
      - postgres_data:/var/lib/postgresql/data # Сохранение данных PostgreSQL
      # Если нужны init-скрипты (например, для создания расширений, если gen_random_uuid() не работает):
      # - ./build/postgres/init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:5432" # Проброс порта на хост
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -q"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - semantica_network

  orchestrator:
    container_name: semantica-orchestrator
    build:
      context: . # Корень вашего проекта
      dockerfile: ./build/orchestrator/Dockerfile # Путь к Dockerfile Оркестратора
    ports:
      # Внешний порт хоста : внутренний порт контейнера (только номер порта)
      - "${ORCHESTRATOR_HOST_PORT:-8080}:${ORCHESTRATOR_INTERNAL_PORT_NUMBER:-8080}"
    environment:
      RABBITMQ_URL: amqp://${RABBITMQ_DEFAULT_USER:-guest}:${RABBITMQ_DEFAULT_PASS:-guest}@rabbitmq:5672/
      POSTGRES_DSN: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      MIGRATIONS_DIR: ${MIGRATIONS_DIR:-/app/db/migrations}
      # Передаем порт, который приложение должно слушать внутри контейнера (с двоеточием)
      ORCHESTRATOR_API_PORT: ":${ORCHESTRATOR_INTERNAL_PORT_NUMBER:-8080}"
      # LOG_LEVEL: ${LOG_LEVEL:-INFO}
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - semantica_network

  worker-crawler:
    container_name: semantica-worker-crawler
    build:
      context: .
      dockerfile: ./build/worker-crawler/Dockerfile
    environment:
      RABBITMQ_URL: amqp://${RABBITMQ_DEFAULT_USER:-guest}:${RABBITMQ_DEFAULT_PASS:-guest}@rabbitmq:5672/
      # LOG_LEVEL: ${LOG_LEVEL:-INFO}
    depends_on:
      rabbitmq:
        condition: service_healthy
      # postgres: # Если краулеру нужен доступ к БД (пока нет)
      #   condition: service_healthy
    restart: unless-stopped
    networks:
      - semantica_network

# Определение именованных volumes для сохранения данных
volumes:
  rabbitmq_data:
    driver: local # Явно указываем драйвер (хотя это по умолчанию)
  postgres_data:
    driver: local

# Определение общей сети для всех сервисов
networks:
  semantica_network:
    driver: bridge
